In [219]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [220]:
digits = load_digits()

x = digits.data

In [221]:
y = digits.target

In [222]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [223]:
model1 = LogisticRegression()
model1.fit(x_train,y_train)
model1.score(x_test,y_test)

c:\Users\user\Desktop\Machine_Learning_Codes\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [224]:
model2 = SVC()
model2.fit(x_train,y_train)
model2.score(x_test,y_test)

0.9833333333333333

In [225]:
model3 = RandomForestClassifier()
model3.fit(x_train,y_train)
model3.score(x_test,y_test)

0.9685185185185186

In [226]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [227]:
for train_index, test_index in kf.split([11,12,13,4,5,6,7,8,9,10]):
    print(train_index,test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [228]:
def get_Score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [229]:
get_Score(LogisticRegression(),x_train,x_test,y_train,y_test)

c:\Users\user\Desktop\Machine_Learning_Codes\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [230]:
from sklearn.model_selection import StratifiedKFold

fold = StratifiedKFold(n_splits=5)
score_logistic = []
score_svm = []
score_rf = []

In [231]:
for train_index,test_index in fold.split(x,y):
    x_train,x_test,y_train,y_test = x[train_index],x[test_index],y[train_index],y[test_index]
    
    p = get_Score(LogisticRegression(),x_train,x_test,y_train,y_test)
    score_logistic.append(p)
    q = get_Score(SVC(),x_train,x_test,y_train,y_test)
    score_svm.append(q)
    r = get_Score(RandomForestClassifier(),x_train,x_test,y_train,y_test)
    score_rf.append(r)

c:\Users\user\Desktop\Machine_Learning_Codes\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\user\Desktop\Machine_Learning_Codes\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/mod

In [232]:
print(score_logistic)

[0.9222222222222223, 0.8694444444444445, 0.9415041782729805, 0.9387186629526463, 0.8969359331476323]


In [233]:
print(score_svm)

[0.9611111111111111, 0.9444444444444444, 0.9832869080779945, 0.9888579387186629, 0.9387186629526463]


In [234]:
print(score_rf)


[0.9305555555555556, 0.8972222222222223, 0.958217270194986, 0.958217270194986, 0.9303621169916435]


In [235]:
mean_logisticReg = sum(score_logistic)/5
mean_svm = sum(score_svm)/5
mean_rf = sum(score_rf)/5
print(mean_logisticReg,mean_svm,mean_rf)

0.9137650882079852 0.9632838130609718 0.9349148870318787


In [239]:
from sklearn.model_selection import cross_val_score

In [240]:
cross_val_score(LogisticRegression(),x,y,cv=5).mean()

c:\Users\user\Desktop\Machine_Learning_Codes\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\user\Desktop\Machine_Learning_Codes\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/mod

np.float64(0.9137650882079852)

In [243]:
cross_val_score(SVC(),x,y,cv=5).mean()

np.float64(0.9632838130609718)